apiVersion: v1
kind: PersistentVolume
metadata:
  name: data
  labels:
    app: elasticsearch
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/"
