apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-data-dir
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi
  hostPath:
    path: /data/mongo