apiVersion: v1
kind: PersistentVolume
metadata:
  name: cassandra-data
  labels:
    app: cassandra
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/cassandra_data"
